name: deploy comanda.subscriptions to production environment

on:
  push:
    branches: [master]
    paths:
      - 'Boundaries/Comanda.Subscriptions/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Boundaries/Comanda.Subscriptions

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: build docker image
        run: |
          docker build -t httpsrichardy/comanda.subscriptions:latest .

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: push docker image
        run: docker push httpsrichardy/comanda.subscriptions:latest

      - name: deploy via easypanel webhook
        run: |
          curl -X POST ${{ secrets.SUBSCRIPTIONS_PRODUCTION_DEPLOY_URL }}
