name: workflow â€” trigger comanda.subscriptions production deployment

on:
  push:
    branches: [master]
    paths:
      - 'Boundaries/Comanda.Subscriptions/**'

jobs:
  call-deploy:
    uses: ./.github/workflows/production-deployment.yml
    with:
      service_path: Boundaries/Comanda.Subscriptions
      image_name: httpsrichardy/comanda.subscriptions
      deploy_url_secret: SUBSCRIPTIONS_PRODUCTION_DEPLOY_URL
    secrets: inherit
